{
  allUsers(first:5) {
    edges {
      node {
        username
        email
      }
      cursor
    }
    pageInfo {
      startCursor
      endCursor
      hasNextPage
      hasPreviousPage
    }
  }
}