{
  allUsers(first:5, after:"YXJyYXljb25uZWN0aW9uOjQ=") {
    edges {
      node {
        username
        email
      }
      cursor
    }
    pageInfo {
      startCursor
      endCursor
      hasNextPage
      hasPreviousPage
    }
  }
}